"""add_organization_name_to_users

Revision ID: 79650d9e4249
Revises: 5d8ef31ab17c
Create Date: 2026-06-29 11:06:52.512536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79650d9e4249'
down_revision: Union[str, Sequence[str], None] = '5d8ef31ab17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organization_name')
    # ### end Alembic commands ###
